project_id = "mk-bet"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[local_smtp]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.vector]
enabled = false

[auth]
enabled = true
site_url = "https://mk-bet.vercel.app"
additional_redirect_urls = [
  "http://localhost:3000/**",
  "http://127.0.0.1:3000/**",
  "http://localhost:3100/**",
  "http://127.0.0.1:3100/**",
  "https://mk-bet.vercel.app/auth/callback"
]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false
minimum_password_length = 10

[auth.rate_limit]
email_sent = 100

[auth.email]
enable_confirmations = false
max_frequency = "1m0s"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
